basePath: /
definitions:
  models.Receita:
    properties:
      descricao:
        type: string
      id:
        type: string
      ingredientes:
        items:
          type: string
        type: array
      instrucoes:
        type: string
      nome:
        type: string
    type: object
host: localhost:5555
info:
  contact: {}
  description: Esta é a API para gerenciamento de receitas com JWT
  title: API Receitas Culinárias
  version: "1.0"
paths:
  /api/receitas:
    get:
      description: Retorna todas as receitas cadastradas no banco de dados
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Receita'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Lista todas as receitas
      tags:
      - receitas
    post:
      consumes:
      - application/json
      description: Adiciona uma nova receita com nome, descrição, ingredientes e instruções
      parameters:
      - description: Dados da nova receita
        in: body
        name: receita
        required: true
        schema:
          $ref: '#/definitions/models.Receita'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Receita'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Cria uma nova receita
      tags:
      - receitas
  /api/receitas/{id}:
    delete:
      description: Remove uma receita do banco de dados pelo ID
      parameters:
      - description: ID da receita (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Deleta uma receita
      tags:
      - receitas
    put:
      consumes:
      - application/json
      description: Atualiza os dados de uma receita existente
      parameters:
      - description: ID da receita (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Dados atualizados da receita
        in: body
        name: receita
        required: true
        schema:
          $ref: '#/definitions/models.Receita'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Receita'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Atualiza uma receita
      tags:
      - receitas
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
